package com.mobdeve.s11.group16.foodstop

enum class Keys {
   IMAGE_KEY, TITLE_KEY, USERNAME_KEY, DATE_KEY, BODY_KEY, FAVORITE_KEY, POSITION_KEY,
   DESCRIPTION_KEY, INGREDIENT_KEY, PROCEDURE_KEY, EMAIL_KEY, PASSWORD_KEY,
}